import { ApiProperty } from '@nestjs/swagger';
import { IsString, IsAlphanumeric, Length } from 'class-validator';

export class JoinClassDto {
    @ApiProperty({
        description: 'The 6-character class join code',
        example: 'A1B2C3',
    })
    @IsString()
    @IsAlphanumeric()
    @Length(6, 6)
    joinCode: string;
}

export class JoinClassByTokenDto {
    @ApiProperty({
        description: 'Join token generated by the invite link',
        example: 'c8172f10-423f-4efb-a312-0da9123cd932',
    })
    @IsString()
    token: string;
}